// <auto-generated />
using System;
using AssigmentC4_TrinhHuuThanh.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssigmentC4_TrinhHuuThanh.Migrations
{
    [DbContext(typeof(AssigmentThanhC4Context))]
    [Migration("20260311215911_updateDB1")]
    partial class updateDB1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.ChiTietDonHang", b =>
                {
                    b.Property<int>("ChiTietDonHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietDonHangID"));

                    b.Property<int>("DonHangID")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SanPhamID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ChiTietDonHangID");

                    b.HasIndex("DonHangID");

                    b.HasIndex("SanPhamID");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.ChiTietGioHang", b =>
                {
                    b.Property<int>("ChiTietGioHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietGioHangID"));

                    b.Property<int>("GioHangID")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ChiTietGioHangID");

                    b.HasIndex("GioHangID");

                    b.HasIndex("SanPhamID");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.DanhMuc", b =>
                {
                    b.Property<int>("DanhMucID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhMucID"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DanhMucID");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            DanhMucID = 1,
                            MoTa = "Máy ảnh DSLR chuyên nghiệp",
                            TenDanhMuc = "Máy ảnh DSLR"
                        },
                        new
                        {
                            DanhMucID = 2,
                            MoTa = "Máy ảnh mirrorless không gương lật",
                            TenDanhMuc = "Máy ảnh Mirrorless"
                        },
                        new
                        {
                            DanhMucID = 3,
                            MoTa = "Máy ảnh compact cho du lịch",
                            TenDanhMuc = "Máy ảnh du lịch"
                        },
                        new
                        {
                            DanhMucID = 4,
                            MoTa = "Ống kính cho máy ảnh",
                            TenDanhMuc = "Ống kính"
                        },
                        new
                        {
                            DanhMucID = 5,
                            MoTa = "Phụ kiện máy ảnh",
                            TenDanhMuc = "Phụ kiện"
                        });
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.DonHang", b =>
                {
                    b.Property<int>("DonHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonHangID"));

                    b.Property<bool>("DaThanhToan")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DonHangID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.GioHang", b =>
                {
                    b.Property<int>("GioHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GioHangID"));

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungID")
                        .HasColumnType("int");

                    b.HasKey("GioHangID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungID"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("QuyenID")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NguoiDungID");

                    b.HasIndex("QuyenID");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            NguoiDungID = 1,
                            DiaChi = "123 Đường ABC, Quận 1, TP.HCM",
                            Email = "admin@camerashop.vn",
                            HoTen = "Quản trị viên",
                            MatKhau = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuyenID = 1,
                            SoDienThoai = "0123456789",
                            TenDangNhap = "admin"
                        },
                        new
                        {
                            NguoiDungID = 2,
                            DiaChi = "456 Đường XYZ, Quận 2, TP.HCM",
                            Email = "customer@example.com",
                            HoTen = "Nguyễn Văn A",
                            MatKhau = "5o/ZKF3XYRonqXJbFBSdxIu27p2K8b8Y8M+6yUNlJIA=",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuyenID = 2,
                            SoDienThoai = "0987654321",
                            TenDangNhap = "customer"
                        });
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.QuyenNguoiDung", b =>
                {
                    b.Property<int>("QuyenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuyenID"));

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QuyenID");

                    b.ToTable("QuyenNguoiDungs");

                    b.HasData(
                        new
                        {
                            QuyenID = 1,
                            TenQuyen = "Admin"
                        },
                        new
                        {
                            QuyenID = 2,
                            TenQuyen = "Khách hàng"
                        });
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.SanPham", b =>
                {
                    b.Property<int>("SanPhamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SanPhamID"));

                    b.Property<int?>("DanhMucID")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("HinhAnh")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ThuongHieuID")
                        .HasColumnType("int");

                    b.Property<int>("TonKho")
                        .HasColumnType("int");

                    b.HasKey("SanPhamID");

                    b.HasIndex("DanhMucID");

                    b.HasIndex("ThuongHieuID");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            SanPhamID = 1,
                            DanhMucID = 1,
                            Gia = 32990000m,
                            MoTa = "Máy ảnh DSLR 32.5MP, video 4K",
                            NgayThem = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Canon EOS 90D",
                            TonKho = 15
                        },
                        new
                        {
                            SanPhamID = 2,
                            DanhMucID = 1,
                            Gia = 75990000m,
                            MoTa = "Máy ảnh DSLR 45.7MP Full-frame",
                            NgayThem = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Nikon D850",
                            TonKho = 8
                        },
                        new
                        {
                            SanPhamID = 3,
                            DanhMucID = 2,
                            Gia = 63990000m,
                            MoTa = "Máy ảnh Mirrorless 33MP, chống rung 5 trục",
                            NgayThem = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sony A7 IV",
                            TonKho = 12
                        },
                        new
                        {
                            SanPhamID = 4,
                            DanhMucID = 2,
                            Gia = 54990000m,
                            MoTa = "Máy ảnh Mirrorless 40MP, màu Fuji Film Simulation",
                            NgayThem = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Fujifilm X-T5",
                            TonKho = 10
                        },
                        new
                        {
                            SanPhamID = 5,
                            DanhMucID = 3,
                            Gia = 18990000m,
                            MoTa = "Máy ảnh compact 20MP, video 4K",
                            NgayThem = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Canon PowerShot G7 X Mark III",
                            TonKho = 20
                        },
                        new
                        {
                            SanPhamID = 6,
                            DanhMucID = 3,
                            Gia = 31990000m,
                            MoTa = "Máy ảnh compact cao cấp 20MP",
                            NgayThem = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sony RX100 VII",
                            TonKho = 15
                        },
                        new
                        {
                            SanPhamID = 7,
                            DanhMucID = 4,
                            Gia = 3290000m,
                            MoTa = "Ống kính fix khẩu độ lớn",
                            NgayThem = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Canon EF 50mm f/1.8 STM",
                            TonKho = 30
                        },
                        new
                        {
                            SanPhamID = 8,
                            DanhMucID = 4,
                            Gia = 53990000m,
                            MoTa = "Ống kính zoom chuyên nghiệp",
                            NgayThem = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sony FE 24-70mm f/2.8 GM",
                            TonKho = 5
                        },
                        new
                        {
                            SanPhamID = 9,
                            DanhMucID = 5,
                            Gia = 4590000m,
                            MoTa = "Chân máy nhôm chuyên nghiệp",
                            NgayThem = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Manfrotto Tripod 290 Xtra",
                            TonKho = 25
                        },
                        new
                        {
                            SanPhamID = 10,
                            DanhMucID = 5,
                            Gia = 1290000m,
                            MoTa = "Thẻ nhớ SDXC UHS-I tốc độ cao",
                            NgayThem = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "SanDisk Extreme Pro 128GB",
                            TonKho = 50
                        });
                });

            modelBuilder.Entity("AssigmentC4_TrinhHuuThanh.Models.DataModels.ChiTietSanPham", b =>
                {
                    b.Property<int>("ChiTietSanPhamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietSanPhamID"));

                    b.Property<string>("CamBien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChongRung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DoPhanGiai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISO")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KetNoi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KhauDo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManHinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OngKinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SanPhamID")
                        .HasColumnType("int");

                    b.Property<string>("TrongLuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Video")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ChiTietSanPhamID");

                    b.HasIndex("SanPhamID")
                        .IsUnique();

                    b.ToTable("chiTietSanPhams");
                });

            modelBuilder.Entity("AssigmentC4_TrinhHuuThanh.Models.DataModels.TheoDoiDonHang", b =>
                {
                    b.Property<int>("TheoDoiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TheoDoiID"));

                    b.Property<int>("DonHangID")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViTri")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TheoDoiID");

                    b.HasIndex("DonHangID");

                    b.ToTable("TheoDoiDonHang");
                });

            modelBuilder.Entity("AssigmentC4_TrinhHuuThanh.Models.DataModels.ThuongHieu", b =>
                {
                    b.Property<int>("ThuongHieuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThuongHieuID"));

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ThuongHieuID");

                    b.ToTable("thuongHieus");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.ChiTietDonHang", b =>
                {
                    b.HasOne("Assigmemt_Thanh_C4.Models.DataModels.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assigmemt_Thanh_C4.Models.DataModels.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("SanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.ChiTietGioHang", b =>
                {
                    b.HasOne("Assigmemt_Thanh_C4.Models.DataModels.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("GioHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assigmemt_Thanh_C4.Models.DataModels.SanPham", "SanPham")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("SanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.DonHang", b =>
                {
                    b.HasOne("Assigmemt_Thanh_C4.Models.DataModels.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.GioHang", b =>
                {
                    b.HasOne("Assigmemt_Thanh_C4.Models.DataModels.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.NguoiDung", b =>
                {
                    b.HasOne("Assigmemt_Thanh_C4.Models.DataModels.QuyenNguoiDung", "Quyen")
                        .WithMany()
                        .HasForeignKey("QuyenID");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.SanPham", b =>
                {
                    b.HasOne("Assigmemt_Thanh_C4.Models.DataModels.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucID");

                    b.HasOne("AssigmentC4_TrinhHuuThanh.Models.DataModels.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("ThuongHieuID");

                    b.Navigation("DanhMuc");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("AssigmentC4_TrinhHuuThanh.Models.DataModels.ChiTietSanPham", b =>
                {
                    b.HasOne("Assigmemt_Thanh_C4.Models.DataModels.SanPham", "SanPham")
                        .WithOne("ChiTietSanPham")
                        .HasForeignKey("AssigmentC4_TrinhHuuThanh.Models.DataModels.ChiTietSanPham", "SanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("AssigmentC4_TrinhHuuThanh.Models.DataModels.TheoDoiDonHang", b =>
                {
                    b.HasOne("Assigmemt_Thanh_C4.Models.DataModels.DonHang", "DonHang")
                        .WithMany("TheoDoiDonHangs")
                        .HasForeignKey("DonHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("TheoDoiDonHangs");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("Assigmemt_Thanh_C4.Models.DataModels.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("ChiTietSanPham");
                });

            modelBuilder.Entity("AssigmentC4_TrinhHuuThanh.Models.DataModels.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
